"""update audit logs

Revision ID: 619f279a1162
Revises: 722e196241dd
Create Date: 2026-08-05 14:17:43.155928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619f279a1162'
down_revision: Union[str, Sequence[str], None] = '722e196241dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('old_state', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_state', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'old_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'new_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'new_state')
    op.drop_column('audit_logs', 'old_state')
    # ### end Alembic commands ###
