"""add flag_id and environment_id to audit logs

Revision ID: 722e196241dd
Revises: 9d877eeb5ae5
Create Date: 2026-08-05 11:44:13.910632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722e196241dd'
down_revision: Union[str, Sequence[str], None] = '9d877eeb5ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
