"""audit logs

Revision ID: 9d877eeb5ae5
Revises: a5cf875ed7e8
Create Date: 2026-08-05 11:31:51.646313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d877eeb5ae5'
down_revision: Union[str, Sequence[str], None] = 'a5cf875ed7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('flag_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.alter_column('targeting_rules', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targeting_rules', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'environment_id')
    op.drop_column('audit_logs', 'flag_id')
    # ### end Alembic commands ###
